version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3307'
    environment:
       MYSQL_DATABASE: 'botanydb'
       MYSQL_USER: 'django-test'
       MYSQL_PASSWORD: 'djangobot@CAS'
       MYSQL_ROOT_PASSWORD: 'botCAS2024'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/collection_explorer
    ports:
      - "8000:8000"
    depends_on:
      - db