# Generated by Django 4.2.7 on 2024-08-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
