# Generated by Django 4.2.7 on 2024-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "universal_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "original_path",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("redacted", models.IntegerField(blank=True, null=True)),
                (
                    "internal_filename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=8192, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("collection", models.CharField(blank=True, max_length=50, null=True)),
                ("orig_md5", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "images",
                "managed": False,
            },
        ),
    ]
